weather/urls.py
from django.urls import path
from .views import home_view, forecast_view, prediction_view, PredictionView


app_name = 'weather'

urlpatterns = [
    path('', home_view, name='home'),
    path('forecast/', forecast_view, name='forecast'),
    path('prediction/', prediction_view, name='prediction')
]

weather_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('weather.urls', namespace='weather')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.contrib.auth.models import User
from .utils import current_weather_data, OpenWeatherMap
import json

# Create your models here.


class Cities(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField()
    #weather = JSONField()

    class Meta:
        ordering = ['-id']

    def get_weather(self, units, language):
        data = current_weather_data(self.name, units, language)
        return data

    def __str__(self):
        return self.name

weather/views.py
from django.shortcuts import render
import json
import urllib.request, urllib.parse

from .models import Cities
from .utils import current_weather_data, OpenWeatherMap, serialize_page

import random
import asyncio

from cursor_pagination import CursorPaginator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core import serializers

# Create your views here.

languages = {
            'Afrikaans' : 'af',
            'Albanian' : 'al',
            'Arabic' : 'ar',
            'Azerbaijani' : 'az', 
            'Bulgarian' : 'bg', 
            'Catalan' : 'ca', 
            'Czech' : 'cz', 
            'Danish' : 'da',
            'German' : 'de',
            'Greek' : 'el',
            'English' : 'en',
            'Basque' : 'eu',
            'Persian' : 'fa',
            'Finnish' : 'fi',
            'French' : 'fr',
            'Galician' : 'gl',
            'Hebrew' : 'he',
            'Hindi' : 'hi',
            'Croatian' : 'hr',
            'Hungarian' : 'hu',
            'Indonesian' : 'id',
            'Italian' : 'it',
            'Japanese' : 'ja',
            'Korean' : 'kr',
            'Latvian' : 'la',
            'Lithuanian' : 'lt',
            'Macedonian' : 'mk',
            'Norwegian' : 'no',
            'Dutch' : 'nl',
            'Polish' : 'pl',
            'Portuguese' : 'pt',
            'Português Brasil' : 'pt_br', 
            'Romanian' : 'ro',
            'Russian' : 'ru',
            'Swedish' : 'sv',
            'Slovak' : 'sk',
            'Slovenian' : 'sl',
            'Spanish' : 'sp',
            'Serbian' : 'sr',
            'Thai' : 'th',
            'Turkish' : 'tr',
            'Ukrainian' : 'uk',
            'Vietnamese' : 'vi',
            'Chinese Simplified' : 'zh_cn', 
            'Chinese Traditional' : 'zh_tw', 
            'Zulu' : 'zu',
            }

cities = ['Honolulu', 'Cape Town', 'Moscow', 'New York', 'London', 'Los Angeles', 'Rio De Janeiro', 'Jakarta', 'Shanghai', 'Sidney', 'Tokyo', 'Buenos Aires', 'Paris', 'Nairobi']

from django.views.generic.list import ListView

class PredictionView(ListView):
    model = Cities
    paginate_by = 2
    context_object_name = 'cities'
    template_name = 'weather/prediction.html'

def prediction_view(request):

    #cursor = request.GET.get('cursor')
    # page_size = 2
    # paginator = CursorPaginator(qs, ordering=('-id', '-name'))
    # page = paginator.page(first=page_size, after=cursor)
    # has_next = page.has_next

    units = request.GET.get('units') if request.GET.get('units') != None else 'imperial'
    language = request.GET.get('language') if request.GET.get('language') != None else 'en'

    qs = Cities.objects.all().order_by('-id')
    page = request.GET.get('page', 1)
    paginator = Paginator(qs, 1)

    try:
        cities = paginator.page(page)
    except PageNotAnInteger:
        cities = paginator.page(1)
    except EmptyPage:
        cities = paginator.page(paginator.num_pages)

    # if has_next == False:
    #     page = paginator.page(first=page_size, after=paginator.cursor(page[0]))
    #     #page = paginator.page(first=page_size, after='M3xMb3MgQW5nZWxlcw==')
    # else:

    data = {
        #'json': serialize_page(page),
        'languages': languages,
        'units': units,
        'language': language,
        'qs': qs,
        'cities': cities,
        'num_pages': paginator.page(paginator.num_pages),
        'page': page,
        #'hasNext': page.has_next,
        #'hasNext': has_next,
        #'last_cursor': paginator.cursor(page[-1]),
        #'lastCursor': paginator.cursor(page[-1]),
    }
    return render(request, 'weather/prediction.html', data)


def home_view(request):
    if request.method == 'POST':
        form_city = request.POST['city']
        stringified_city = str(form_city)
        cities = Cities.objects.all()
        city = cities.get(name=stringified_city)

    else:
        city = None

    

    units = request.GET.get('units') if request.GET.get('units') != None else 'imperial'
    language = request.GET.get('language') if request.GET.get('language') != None else 'English'

    qs = Cities.objects.all().order_by('-id')


    #city = qs.get(name=city_name)
    page = request.GET.get('page', 1)
    paginator = Paginator(qs, 1)

    try:
        cities = paginator.page(page)
    except PageNotAnInteger:
        cities = paginator.page(1)
    except EmptyPage:
        cities = paginator.page(paginator.num_pages)

    context = {
        'languages': languages,
        'cities': cities,
        'data': serializers.serialize('json', cities),
        #'city': city,
        'units': units,
        'language': language,
        'num_pages': paginator.page(paginator.num_pages),
        'page': page,
    }
    
    return render(request, 'weather/home.html', context)


def forecast_view(request):

    units = request.GET.get('units') if request.GET.get('units') != None else 'imperial'
    language = request.GET.get('language') if request.GET.get('language') != None else 'English'
    
    if request.method == 'POST' and 'get_info' in request.POST:

        coords = request.POST['coords']
        lat, lon = coords.split(' ')

        owm = OpenWeatherMap()
        owm_forecast = OpenWeatherMap()

        current_weather = owm.set_up(lat, lon, "weather", units, languages[language])
        serialized_current_weather = json.dumps(current_weather)
        
        owm_forecast.set_up(lat, lon, 'forecast', units=units, language=languages[language])
        forecast = owm_forecast.get_forecast_improved()
        serialized_forecast = json.dumps(forecast)


        context = {
            'serialized_current_weather': serialized_current_weather,
            'serialized_forecast': serialized_forecast,
            'languages': languages,
            'units': units,
            'lat': lat,
            'lon': lon,
        }
    else:
        context = {
            'languages': languages,
        }
    return render(request, 'weather/forecast.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Web-App for world wide real time weather and 5 days / 3 hours weather forecasts">

  
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"/>
  
  <!-- JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" defer></script>
  
  <!-- favicon -->
  <link rel="shortcut icon" href="{% static 'favicon_io/favicon.ico' %}" />
  
  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% block styles %}
  {% endblock styles %}

  <!-- JS -->
  {% block scripts %}
  {% endblock scripts %}

  <title>Weather App | {% block custom_title %}{% endblock custom_title %}</title>
</head>
<body>
  {% include 'navbar.html' %}

  {% block content %}{% endblock content %}
</body>
</html>

templates/navbar.html
{% load static %}

{% url 'weather:home' as path_to_home %}


{% block scripts %}
  <script src="{% static 'js/navigation.js' %}" defer></script>
{% endblock scripts %}
  

{% block styles %}
  <link rel="stylesheet" href="{% static 'css/navigation.css' %}">
{% endblock styles %}

<nav class="nav">
  <a class="home-a" aria-label="Home link" href="{{path_to_home}}"><i class="bi bi-house-door"></i></a>
  <h1>Weather App</h1>
  <div class="selection-div">

    <form action="" method="GET">
      <div class="units-div">
        <label for="units">Units:</label>
        <select name="units" id="units-selection" onchange="updateUrl('units')">
          <option value="imperial">Imperial</option>
          <option value="metric">Metric</option>
        </select>
      </div>
      <div class="language-div">
        <label for="language">Language:</label>
        <select name="language" id="language-selection" onchange="updateUrl()">
          {% for language in languages %}
          <option value="{{language}}">{{language}}</option>
          {% endfor %}
        </select>
      </div>
    </form>
  </div>
</nav>

weather/templates/weather/forecast.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'weather/css/forecast.css' %}">
{% endblock styles %}

{% block scripts %}
  <script src="{% static 'weather/js/forecast.js' %}"
  data-weather="{{serialized_current_weather}}"
  data-forecast="{{serialized_forecast}}"
  data-units="{{units}}"
  defer></script>
{% endblock scripts %}

{% block custom_title%}
  Forecast
{% endblock custom_title%}


{% block content %}

<div class="alert alert-warning" role="alert">
</div>

<div class="form-container">
  <div class="input-div">
    <form action="" method="POST" class="form">
    {% csrf_token %}
      <div class="autocomplete-container" id="autocomplete-container">
        <label for="autocomplete" class="visually-hidden">Autocomplete input</label>
        <input autocomplete="off" id="autocomplete-input" name="city" type="text" placeholder="Search"/>
        <label for="coords" class="visually-hidden">Hidden coordinates input</label>
        <input type="hidden" name="coords" id="hidden-input">
        <button aria-label="clear predictions" class="clear-button"><i class="bi bi-x-square"></i></button>
      </div>
      <button aria-label="search weather" class="btn search-btn" type="submit" name="get_info">
        <i class="bi bi-search"></i>
      </button>
    <form>
  </div>
  <button aria-label="add optional filters" class="btn filter-btn" data-dropdown-btn name="filters">
    <i class="bi bi-filter"></i>
  </button>
</div>

<div class="filter-dropdown">
  <div class="dropdown-selection">
    <div class="filters">
      <h3 class="dropdown-heading">Location</h3>
      <h6>Timezone <label for="timezone" class="visually-hidden">Timezone</label> <input type="checkbox" name="timezone"></h6>
      <h6>Sunrise — Sunset <label for="sunrise-sunset" class="visually-hidden">Sunrise-Sunset</label><input type="checkbox" name="sunrise-sunset"></h6>
      <h6>Coordinates <label for="coords" class="visually-hidden">Coordinates</label><input type="checkbox" name="coords"></h6>
    </div>

    <div class="filters">
      <h3 class="dropdown-heading">Weather</h3>
        <h6>Perceived Temperature <label for="perceived temperature" class="visually-hidden">Perceived temperature</label><input type="checkbox" name="temp-perceived"></h6>
        <h6>Min - Max Temperature <label for="min -max temp" class="visually-hidden">Min - Max Temp</label><input type="checkbox" name="temp-min-max"></h6>
        <h6>Pressure <label for="pressure" class="visually-hidden">Pressure</label><input type="checkbox" name="pressure"></h6>
        <h6>Humidity <label for="humidity" class="visually-hidden">Humidity</label><input type="checkbox" name="humidity"></h6>
        <h6>Visibility <label for="visibility" class="visually-hidden">Visibility</label><input type="checkbox" name="visibility"></h6>
    </div>
  </div>
</div>


{% if lat is not None %}
    
  <main class="weather-data-div">

    <div class="current-weather-container">
      <div class="location-related">
        <h2 id="location-title"></h2>
        <h3 id="time"></h3>
        <h5 id="timezone">Timezone: </h5>
        <h5 id="sunrise-sunset"> Sunrise — Sunset: </h5>
        <h5 id="coords"> Coordinates: </h5>
      </div>

      <div class="weather-related">
        <h3>
          <img id="weather-icon" src="">
        </h3>
        <h3 id="weather-description"></h3>
        <h3 id="temperature">Temperature:</h3>
        <div class="temperature-details optional">
          <h5 id="temp-perceived">Perceived temperature:</h5>
          <h5 id="temp-min-max">Min / Max:</h5>
        </div>
      </div>
      
      <div class="various optional">
        <h5 id="pressure">Pressure: </h5>
        <h5 id="humidity">Humididty:</h5>
        <h5 id="visibility">Visibility:</h5>
      </div>
    </div>

    <div class="forecast">
      <div class="forecast-slider"></div>
    </div>

  <main/>
{% endif %}
  

{% endblock content %}

weather/templates/weather/home.html
{% extends 'base.html' %}
{% load static %}

{% load get_weather_info %}

{% url 'weather:forecast' as path_to_forecast %}

{% block custom_title %}
Home
{% endblock custom_title %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'weather/css/home.css' %}">
{% endblock styles %}


{% block scripts %}
  <script src="{% static 'weather/js/home.js' %}" 
  data-pages='{{ num_pages }}'
  defer></script>
{% endblock scripts %}
  
{% block content %} 
<main class="main">
  
  <div id="outside-container">
    <div id="inside-container" class="cf">
      {% for city in cities %}

      {% get_weather city.name units language as weather_info %}

      
      {% if units == 'metric' %}
      <div class="items" >
        <div class="data-div">
          <ul>
            <li><b>{% destructure weather_info 'location' 'city' %}</b> </li>
            <li class="weather-desciprion">{% destructure weather_info 'weather' 'description' %}</li>
            <img src="{% destructure weather_info 'weather' 'icon' %}" alt=" " class="weather-icon">
            <li>{% destructure weather_info 'main' 'temperature' %}°C</li>
            <li>{% destructure weather_info 'location' 'time' %}</li>
          </ul>
        </div>
        <img class="carousel-img" src="{{city.image.url}}" alt="No image available">
      </div>
      {% else %}
      <div class="items" >
        <div class="data-div">
          <ul>
            <li><b>{% destructure weather_info 'location' 'city' %}</b> </li>
            <li class="weather-desciprion">{% destructure weather_info 'weather' 'description' %}</li>
            <img src="{% destructure weather_info 'weather' 'icon' %}" alt=" " class="weather-icon">
            <li>{% destructure weather_info 'main' 'temperature' %}°F</li>
            <li>{% destructure weather_info 'location' 'time' %}</li>
          </ul>
        </div>
        <img class="carousel-img" src="{{city.image.url}}" alt="No image available">
      </div>
      {% endif %}

      {% endfor %}
    </div>
  </div>
  
  <div id="directions">
    <h4 id="slide-button"></h4>
    <a id="next-slide" href="?page="></a>
  </div>

</main>


<div class="btn-container">
  <div class="btn-div">
      <a class="link" href="{% url 'weather:forecast' %}">
        Forecast
        <i class="bi bi-cloud-sun"></i>
      </a>
  </div>

</div>

{% endblock content %}